### PR TITLE
Rename alexkida.cfg to alexkida.zip.cfg

### PR DESCRIPTION
**Pull request by puxxi2003**

### CODE REVIEW

**Comment by cosmo0** [comment]
Nice catch! Thank you! 😄

**Comment by puxxi2003** [comment]
Hi, thanks.
Very nice work of yours.

Here are some more :-)
In artworks are some pics with wrong/strange resolution.
armedf.png----1800x1013
citycon.png----1923x1080
dotron.png----1356x1017
sprint1.png----4000x2104
varth.png----1800x1013
wcbowldx.png----1852x1043
and
410 images are useless big (2560x1440 and 3480x2160).

Before i use them on the pi, i resize them all to 1920x1080.

**Comment by cosmo0** [comment]
Thanks, I haven't much worked on the artworks pack yet (I have to admit it's not what I prefer), but I'll make a note to check the images sizes.

Currently I'm checking the realistic pack one game by one, to make sure the screen positions are correct: sometimes they're off by 100px (error on my part), sometimes the games do not handle overscan and I have to slightly reduce the screen size, etc. It's especially important on the overlays with "over-screen" bezel that can mask important parts of the screen (see [Missile Command](https://github.com/cosmo0/retropie-arcade-overlays/blob/master/overlays-realistic/configs/all/retroarch/overlay/arcade/missile2.png)).

If you're interested in my progress, you can check my todo list here: https://github.com/cosmo0/retropie-arcade-overlays/projects/1

**Comment by cosmo0** [comment]
@puxxi2003 I have resized all images to 1080p, and removed the "TV bezels" from the artwork pack.

The packs should be done now 😄  ... even though OrionsAngel has JUST released another pack 😓

**Comment by puxxi2003** [comment]
Nice, thanks.
Hope OrionsAngel will release some more and i think he will. :-)
Your hard work will never end, but you do a great job. (collecting them all)

**Comment by cosmo0** [comment]
The latest OrionsAngel pack (32), including the Gold Medal fix, is integrated in the latest release (v1.0.1).

Are overlays like Pokemon ? :stuck_out_tongue:

**Comment by puxxi2003** [comment]
Hi,
have you seen the new "MotionBlue_v6" from David Marti.
The image includes nearly 1000 arcade bezels.

https://mega.nz/#!AR030QBY!cG6rynnPWhy6ZFF-sN4UcRO4QHNsXCvEPbIZm5eNCtc
https://drive.google.com/file/d/1Y2aqJoYfBskwH5A4eB3BRHvYC8epMdwA/view

**Comment by cosmo0** [comment]
Hey! Thanks for the heads up :)
I didn't see this, but it's an image to burn on an SD card... not sure how I can open it, and I don't have a spare SD card to use...

**Comment by puxxi2003** [comment]
Thats no prob, use 7zip.   "https://www.7-zip.org/"
Open the *.img in 7zip, there you see the 2 partitions (fat+ext4), you now simply click on the partition you want to open. Voila.
Most overlays are the same as yours, but some are very nice, like DK.

Also there is an Angelpack 33, dont wanna rush you. :-)

**Comment by cosmo0** [comment]
Yeah, I forgot to say that I use a Mac, so most Windows tools (7zip, IsoBuster etc) are out of the question :/

I'll try to extract it at work.

I added the OrionsAngel pack 33 yesterday ;) I haven't created a release, I won't do a new one every time.

**Comment by cosmo0** [comment]
Conversation continued here: https://github.com/cosmo0/retropie-arcade-overlays/issues/2 :)

**Pull request merged**
